"""
src/music_recommender.py
Curated Bollywood song list per emotion + recommendation logic.
YouTube IDs are used to open songs directly on YouTube.
"""
import random

# ── SONG LIBRARY ──────────────────────────────────────────────────────────────
# Each entry: { name, artist, album, youtube_id }
# youtube_id: the 11-char ID from youtube.com/watch?v=XXXXXXXXXXX
SONGS = {'angry': [{'album': 'Gully Boy', 'artist': 'Daler Mehndi', 'name': 'Sher Aaya Sher', 'youtube_id': 'sUgYWORFyOI'},
           {'album': 'Gunday',
            'artist': 'Neha Bhasin, Benny Dayal',
            'name': 'Asalaam-E-Ishqum',
            'youtube_id': 'm78zNllsWxc'},
           {'album': 'Rockstar', 'artist': 'Mohit Chauhan', 'name': 'Sadda Haq', 'youtube_id': 'QTQVG5rSMkQ'},
           {'album': 'Delhi-6', 'artist': 'Harshdeep Kaur', 'name': 'Ik Onkar', 'youtube_id': 'mTHUtEQfDGQ'},
           {'album': 'Bhaag Milkha Bhaag',
            'artist': 'Siddharth Mahadevan',
            'name': 'Zinda',
            'youtube_id': 'Ax0G_P2dSBw'},
           {'album': 'Rang De Basanti', 'artist': 'Naresh Kamath', 'name': 'Roobaroo', 'youtube_id': '1Jm54f7G1FE'},
           {'album': 'Slumdog Millionaire',
            'artist': 'Sukhwinder Singh',
            'name': 'Jai Ho',
            'youtube_id': '2R3XstG35sE'},
           {'album': 'Sultan', 'artist': 'Sukhwinder Singh', 'name': 'Sultan', 'youtube_id': 'abiL84EAWSY'},
           {'album': 'Dangal', 'artist': 'Daler Mehndi', 'name': 'Dangal', 'youtube_id': 'jMfvlh0tjyo'},
           {'album': 'A Flying Jatt',
            'artist': 'Atif Aslam, Sukriti Kakar',
            'name': 'Toota Jo Kabhi Tara',
            'youtube_id': 'GTOdXVfrXF0'},
           {'album': 'Rocky Handsome', 'artist': 'Sonu Nigam', 'name': 'Rocky Handsome', 'youtube_id': 'ze6gbWdefKU'},
           {'album': 'Ram-Leela', 'artist': 'Arijit Singh', 'name': 'Tattad Tattad', 'youtube_id': 'IqpPJ6B2sLE'}],
 'disgust': [{'album': 'Guru', 'artist': 'AR Rahman, Chinmayi', 'name': 'Tere Bina', 'youtube_id': '_mwqXnTEHSc'},
             {'album': 'Murder 2',
              'artist': "Mohit Chauhan, Suzanne D'Mello",
              'name': 'Aye Khuda',
              'youtube_id': 'CM0xzQb4SqU'},
             {'album': 'Tere Ghar Ke Samne',
              'artist': 'Mohammad Rafi',
              'name': 'Dil Ka Bhanwar Kare Pukar',
              'youtube_id': 'hUMWQWp0_kY'},
             {'album': 'Shree 420',
              'artist': 'Manna Dey, Lata Mangeshkar',
              'name': 'Pyaar Hua Ikrar Hua',
              'youtube_id': 'Ortl_xn0lYk'},
             {'album': 'Woh Kaun Thi', 'artist': 'Lata Mangeshkar', 'name': 'Lag Ja Gale', 'youtube_id': 'vB1qh0eUv78'},
             {'album': 'Woh Lamhe', 'artist': 'KK', 'name': 'Kya Mujhe Pyaar Hai', 'youtube_id': 'Gg6NMU4ivXM'},
             {'album': 'Teri Yaadein', 'artist': 'Atif Aslam', 'name': 'Teri Yaadein', 'youtube_id': 'RUed5ltZNoE'},
             {'album': 'Don', 'artist': 'Asha Bhosle', 'name': 'Yeh Mera Dil', 'youtube_id': 'UdGpuqUXSjI'},
             {'album': 'Parichay',
              'artist': 'Kishore Kumar',
              'name': 'Musafir Hoon Yaaron',
              'youtube_id': 'WcsncpEWQZI'},
             {'album': 'Dil Apna Aur Preet Parayi',
              'artist': 'Lata Mangeshkar',
              'name': 'Ajeeb Daastaan Hai Yeh',
              'youtube_id': 'D3b0UU27H4A'},
             {'album': 'Mausam', 'artist': 'Manna Dey', 'name': 'Dil Dhoondta Hai', 'youtube_id': 'Zh-EY7uiD2Q'},
             {'album': 'Ajnabee',
              'artist': 'Kishore Kumar',
              'name': 'Ek Ajnabee Haseena Se',
              'youtube_id': 'b6WLXTkei_k'}],
 'fear': [{'album': 'Bombay',
           'artist': 'Hariharan, Kavita Krishnamurthy',
           'name': 'Tu Hi Re',
           'youtube_id': 'V9mN0qBgEzQ'},
          {'album': 'Julie', 'artist': 'Hariharan', 'name': 'Dil Kya Kare', 'youtube_id': 'W_TqFFWAdPk'},
          {'album': 'Kkusum', 'artist': 'Shaan', 'name': 'Kahin To Hoga', 'youtube_id': '0EWwGn4eyEQ'},
          {'album': 'Zeher', 'artist': 'Atif Aslam', 'name': 'Woh Lamhe', 'youtube_id': '-xjhuuVXcF0'},
          {'album': 'Jab We Met', 'artist': 'Mohit Chauhan', 'name': 'Tum Se Hi', 'youtube_id': 'Cb6wuzOurPc'},
          {'album': 'Jab We Met',
           'artist': 'Ustad Sultan Khan, Shreya Ghoshal',
           'name': 'Aaoge Jab Tum',
           'youtube_id': 'CNZMIhckaA0'},
          {'album': 'Kuch Kuch Hota Hai',
           'artist': 'Udit Narayan, Alka Yagnik',
           'name': 'Koi Mil Gaya',
           'youtube_id': '1S5ncFMuGeY'},
          {'album': 'Veer-Zaara', 'artist': 'Udit Narayan', 'name': 'Main Yahaan Hoon', 'youtube_id': '20eNVXkeb3M'},
          {'album': 'Agneepath', 'artist': 'Sonu Nigam', 'name': 'Abhi Mujh Mein Kahin', 'youtube_id': 'usSA3mPzOJY'},
          {'album': 'Teri Deewani', 'artist': 'Kailash Kher', 'name': 'Teri Deewani', 'youtube_id': 'zZasH6qkn8M'},
          {'album': 'Tum Mile', 'artist': 'KK', 'name': 'Dil Ibaadat', 'youtube_id': 'nF4RAgy6Jkk'},
          {'album': 'Aashiqui 2', 'artist': 'Ankit Tiwari', 'name': 'Sun Raha Hai Na Tu', 'youtube_id': 'z3UHfi9vpbc'}],
 'happy': [{'album': 'Yeh Jawaani Hai Deewani',
            'artist': 'Shalmali Kholgade',
            'name': 'Badtameez Dil',
            'youtube_id': 'II2EO3Nw4m0'},
           {'album': 'Yeh Jawaani Hai Deewani',
            'artist': 'Shalmali Kholgade, Vishal Dadlani',
            'name': 'Balam Pichkari',
            'youtube_id': 'q8XvnGedq-U'},
           {'album': 'Ram-Leela',
            'artist': 'Shreya Ghoshal, Osman Mir',
            'name': 'Nagada Sang Dhol',
            'youtube_id': 'wTFGQVQCGN8'},
           {'album': 'Dil Dhadakne Do',
            'artist': 'Farhan Akhtar, Priyanka Chopra',
            'name': 'Dil Dhadakne Do',
            'youtube_id': '56ZzM4mz4yY'},
           {'album': 'Queen',
            'artist': 'Labh Janjua, Sonu Kakkar',
            'name': 'London Thumakda',
            'youtube_id': 'N5bELC8MXeU'},
           {'album': 'Yeh Jawaani Hai Deewani',
            'artist': 'Rekha Bhardwaj, Vishal Dadlani',
            'name': 'Ghagra',
            'youtube_id': 'T0BQ86ejaGg'},
           {'album': 'Kapoor and Sons',
            'artist': 'Fazilpuria, Badshah',
            'name': 'Kar Gayi Chull',
            'youtube_id': 'iwlUeXLPvf0'},
           {'album': 'Dil Dhadakne Do',
            'artist': 'Shilpa Rao, Nakash Aziz',
            'name': 'Gallan Goodiyaan',
            'youtube_id': 'jCEdTq3j-0U'},
           {'album': 'Gunday',
            'artist': 'Vishal Dadlani, Benny Dayal',
            'name': 'Tune Maari Entriyaan',
            'youtube_id': '2I3NgxDAiqE'},
           {'album': 'Tiger Zinda Hai',
            'artist': 'Vishal Dadlani, Neha Bhasin',
            'name': 'Swag Se Swagat',
            'youtube_id': '7TRFf7uUfhQ'},
           {'album': 'Simmba', 'artist': 'Kumar Sanu, Mika Singh', 'name': 'Aankh Marey', 'youtube_id': '_KhQT-LGb-4'},
           {'album': 'Geetha Govindam',
            'artist': 'Anurag Kulkarni',
            'name': 'Dha Dha 87',
            'youtube_id': 'uefAi7rr9Qk'}],
 'neutral': [{'album': 'Wake Up Sid',
              'artist': 'Amitabh Bhattacharya, Kavita Seth',
              'name': 'Iktara',
              'youtube_id': 'ZlOZktsODpA'},
             {'album': 'Rockstar', 'artist': 'Mohit Chauhan', 'name': 'Tum Ho', 'youtube_id': 'xnfggj-uo94'},
             {'album': 'Rockstar', 'artist': 'Mohit Chauhan', 'name': 'Nadaan Parindey', 'youtube_id': '6MgsHSAcI9k'},
             {'album': 'Rockstar',
              'artist': 'AR Rahman, Javed Ali, Mohit Chauhan',
              'name': 'Kun Faya Kun',
              'youtube_id': 'T94PHkuydcw'},
             {'album': 'Airlift',
              'artist': 'Arijit Singh, Tulsi Kumar',
              'name': 'Soch Na Sake',
              'youtube_id': '3JZ_D3ELwOQ'},
             {'album': 'Aaja Nachle',
              'artist': 'Rahat Fateh Ali Khan',
              'name': 'O Re Piya',
              'youtube_id': 'iv7lcUkFVSc'},
             {'album': 'Om Shanti Om',
              'artist': 'Shreya Ghoshal',
              'name': 'Dastaan-E-Om Shanti Om',
              'youtube_id': 'ymuNkKuToao'},
             {'album': 'Kabhi Alvida Naa Kehna',
              'artist': 'Shafaqat Amanat Ali, Mahalaxmi Iyer',
              'name': 'Mitwa',
              'youtube_id': '2Aj_js8I1hg'},
             {'album': 'Race', 'artist': 'Atif Aslam', 'name': 'Pehli Nazar Mein', 'youtube_id': 'mvJH_REIt20'},
             {'album': 'Jannat', 'artist': 'KK', 'name': 'Zara Sa', 'youtube_id': '-8C_2BBVWk8'},
             {'album': 'Yeh Jawaani Hai Deewani',
              'artist': 'Arijit Singh',
              'name': 'Ilahi',
              'youtube_id': 'hG7dg7dX4hg'},
             {'album': '2 States', 'artist': 'Arijit Singh', 'name': 'Mast Magan', 'youtube_id': 'fXRvluHnjxE'}],
 'sad': [{'album': 'Ae Dil Hai Mushkil',
          'artist': 'Arijit Singh',
          'name': 'Channa Mereya',
          'youtube_id': 'Q1STE4r4Yww'},
         {'album': 'Tamasha',
          'artist': 'Arijit Singh, Alka Yagnik',
          'name': 'Agar Tum Saath Ho',
          'youtube_id': 'dhY8jRNELUc'},
         {'album': 'Ae Dil Hai Mushkil',
          'artist': 'Arijit Singh',
          'name': 'Ae Dil Hai Mushkil',
          'youtube_id': 'dXKrpx6cZQg'},
         {'album': 'Chhichhore', 'artist': 'Arijit Singh', 'name': 'Khairiyat', 'youtube_id': 'ugcfBQ_AUYg'},
         {'album': 'Anjaana Anjaani',
          'artist': 'Shekhar Ravjiani, Mohit Chauhan',
          'name': 'Tujhe Bhula Diya',
          'youtube_id': '-Hb2DeHvvEg'},
         {'album': 'Half Girlfriend',
          'artist': 'Arijit Singh, Shashaa Tirupati',
          'name': 'Phir Bhi Tumko Chaahunga',
          'youtube_id': '_iktURk0X-A'},
         {'album': 'Hamari Adhuri Kahani',
          'artist': 'Arijit Singh',
          'name': 'Hamari Adhuri Kahani',
          'youtube_id': 'IgYF-LjU-MI'},
         {'album': 'Yeh Jawaani Hai Deewani',
          'artist': 'Rekha Bhardwaj, Tochi Raina',
          'name': 'Kabira',
          'youtube_id': 'jHNNMj5bNQw'},
         {'album': 'Kesari', 'artist': 'B Praak', 'name': 'Teri Mitti', 'youtube_id': 'BF2EMEoq27U'},
         {'album': 'October', 'artist': 'Armaan Malik', 'name': 'Theher Ja', 'youtube_id': '_FnTuCPVWPE'},
         {'album': 'Heartless',
          'artist': 'Arijit Singh',
          'name': 'Main Dhoondne Ko Zamaane Mein',
          'youtube_id': 'e5TtS-j_y-k'},
         {'album': 'I Hate Luv Storys',
          'artist': 'Shreya Ghoshal, Sona Mohapatra',
          'name': 'Bahara',
          'youtube_id': 'IT49gtCgsNY'}],
 'surprise': [{'album': 'Dostana',
               'artist': 'Vishal Dadlani, Shankar Mahadevan',
               'name': 'Desi Girl',
               'youtube_id': 'wDIrpvH8MzE'},
              {'album': 'Bombay Velvet',
               'artist': 'Benny Dayal, Shalmali Kholgade',
               'name': 'Subah Hogi',
               'youtube_id': 'eXm7qX6dtXo'},
              {'album': 'Ra.One', 'artist': 'Akon, Hard Kaur', 'name': 'Chammak Challo', 'youtube_id': 'Y943FiZ-Uqw'},
              {'album': 'Jab Tak Hai Jaan',
               'artist': 'Shafaqat Amanat Ali, Shilpa Rao',
               'name': 'Ishq Shava',
               'youtube_id': '571BnqpgWEs'},
              {'album': 'Badrinath Ki Dulhania',
               'artist': 'Badshah, Bappi Lahiri, Anusha Mani',
               'name': 'Tamma Tamma Again',
               'youtube_id': 'FB2lF971TKg'},
              {'album': 'Yeh Jawaani Hai Deewani',
               'artist': 'Arijit Singh, Sunidhi Chauhan',
               'name': 'Dilliwali Girlfriend',
               'youtube_id': '1cDoRqPnCXU'},
              {'album': 'Tees Maar Khan',
               'artist': 'Sunidhi Chauhan',
               'name': 'Sheila Ki Jawani',
               'youtube_id': 'ZTmF2v59CtI'},
              {'album': 'Cocktail',
               'artist': 'Gippy Grewal, Yo Yo Honey Singh',
               'name': 'Angrezi Beat',
               'youtube_id': 'YEf_hnXBbyI'},
              {'album': 'Disco Deewane',
               'artist': 'Nazia Hassan, Biddu',
               'name': 'Disco Deewane',
               'youtube_id': 'QljTHgNSmHQ'},
              {'album': 'Happy New Year',
               'artist': 'Kanika Kapoor, Shah Rukh Khan',
               'name': 'Lovely',
               'youtube_id': 'zdQRwF-Tn_M'},
              {'album': 'Don 2', 'artist': 'Sunidhi Chauhan', 'name': 'Shakira Shakira', 'youtube_id': 'F93LVaWMVbo'},
              {'album': 'Any Body Can Dance',
               'artist': 'Meet Bros Anjjan, Deedar Kaur',
               'name': 'Abcd',
               'youtube_id': 'iVKEcznDqDg'}]}

EMOTION_ALIASES = {
    'happiness': 'happy', 'joy': 'happy', 'excited': 'happy',
    'sadness': 'sad', 'depressed': 'sad', 'unhappy': 'sad',
    'anger': 'angry', 'rage': 'angry', 'frustrated': 'angry',
    'fearful': 'fear', 'scared': 'fear', 'anxiety': 'fear',
    'calm': 'neutral', 'bored': 'neutral',
    'surprised': 'surprise', 'shocked': 'surprise',
    'disgusted': 'disgust',
}


def get_songs(emotion: str, limit: int = 12) -> list:
    """Return a shuffled list of songs for a given emotion."""
    emotion = emotion.lower().strip()
    emotion = EMOTION_ALIASES.get(emotion, emotion)
    songs = SONGS.get(emotion, SONGS['neutral'])
    shuffled = songs[:]
    random.shuffle(shuffled)
    return shuffled[:limit]
